const MEMBERS=['방찬','리노','창빈','현진','한','필릭스','승민','아이엔'];
const defaultCards=[
{id:1,name:'5-STAR 한정 포토카드',album:'★★★★★ (5-STAR)',member:'방찬',style:'',private:false},{id:2,name:'樂-STAR 락스타 포카',album:'樂-STAR',member:'리노',style:'alt',private:false},{id:3,name:'ATE 미공포',album:'ATE',member:'현진',style:'warm',private:false},{id:4,name:'ODDINARY 스캔 포카',album:'ODDINARY',member:'필릭스',style:'alt',private:true},{id:5,name:'MAXIDENT 특전 포카',album:'MAXIDENT',member:'승민',style:'warm',private:false},{id:6,name:'GIANT 일본반 포카',album:'GIANT',member:'아이엔',style:'',private:false}
];
const root=document.querySelector('#app'), picker=document.querySelector('#file-picker');
const state={cards:JSON.parse(localStorage.getItem('skz-cards')||'null')||defaultCards,query:'',member:'전체 멤버',album:'전체 앨범',menuId:null,modal:null,fileTarget:null};
const esc=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const persist=()=>localStorage.setItem('skz-cards',JSON.stringify(state.cards));
function render(){const albums=[...new Set(state.cards.map(c=>c.album))],cards=state.cards.filter(c=>{const text=`${c.name} ${c.album} ${c.member}`.toLowerCase();return(!state.query||text.includes(state.query.toLowerCase()))&&(state.member==='전체 멤버'||c.member===state.member)&&(state.album==='전체 앨범'||c.album===state.album)});root.innerHTML=`<div class="app-shell"><header class="topbar"><div class="brand">SKZ ARCHIVE</div><div class="profile"><div class="avatar">J</div><span>Jane2026_helloW</span><span class="badge">ADMIN</span></div></header><section class="intro"><div><h1>포카 리스트</h1><p>나의 스트레이키즈 컬렉션을 한 곳에서 관리하세요.</p></div><div class="count">${cards.length} CARDS</div></section><section class="controls"><input class="search" value="${esc(state.query)}" oninput="searchCards(this.value)" placeholder="포카, 앨범, 멤버 검색"/><select class="filter" onchange="filterMember(this.value)"><option>전체 멤버</option>${MEMBERS.map(m=>`<option ${state.member===m?'selected':''}>${m}</option>`).join('')}</select><select class="filter" onchange="filterAlbum(this.value)"><option>전체 앨범</option>${albums.map(a=>`<option ${state.album===a?'selected':''}>${esc(a)}</option>`).join('')}</select><button class="add" onclick="openAdd()">+ 포카 추가</button></section><section class="grid">${cards.length?cards.map(cardMarkup).join(''):'<div class="empty">조건에 맞는 포카가 없어요.</div>'}</section></div>${state.modal?modalMarkup():''}`}
function cardMarkup(c){const image=c.image?`<img src="${c.image}" alt="" style="width:100%;height:100%;object-fit:cover">`:'✦';const menu=state.menuId===c.id?`<div class="menu"><button onclick="editCard(${c.id})">이름 변경</button><button onclick="changeImage(${c.id})">파일 변경</button><button onclick="togglePrivate(${c.id})">${c.private?'공개로 전환':'비공개 전환'}</button><button class="danger" onclick="deleteCard(${c.id})">삭제</button></div>`:'';return `<article class="pc-card"><div class="pc-image ${c.style||''}">${image}</div>${c.private?'<span class="private">🔒 비공개</span>':''}<button class="dots" onclick="toggleMenu(${c.id})">⋮</button>${menu}<div class="pc-info"><div class="member">${esc(c.member)}</div><div class="pc-name">${esc(c.name)}</div><div class="album">${esc(c.album)}</div></div></article>`}
function modalMarkup(){const c=state.modal.card;return `<div class="modal-backdrop" onclick="if(event.target===this)closeModal()"><form class="modal" onsubmit="saveCard(event)"><h2>${c.id?'포카 수정':'새 포카 추가'}</h2><div class="field"><label>포카 이름</label><input name="name" required value="${esc(c.name||'')}" placeholder="예: ATE 사운드웨이브 특전"/></div><div class="field"><label>앨범</label><input name="album" required value="${esc(c.album||'')}" placeholder="예: ATE"/></div><div class="field"><label>멤버 선택</label><select name="member">${MEMBERS.map(m=>`<option ${c.member===m?'selected':''}>${m}</option>`).join('')}</select></div><div class="field"><label><input type="checkbox" name="private" ${c.private?'checked':''}/> 비공개 포카로 등록</label></div><div class="modal-actions"><button type="button" class="cancel" onclick="closeModal()">취소</button><button class="save">저장하기</button></div></form></div>`}
function searchCards(v){state.query=v;render()}function filterMember(v){state.member=v;render()}function filterAlbum(v){state.album=v;render()}function toggleMenu(id){state.menuId=state.menuId===id?null:id;render()}function openAdd(){state.modal={card:{member:MEMBERS[0]}};render()}function closeModal(){state.modal=null;render()}function editCard(id){state.menuId=null;state.modal={card:{...state.cards.find(c=>c.id===id)}};render()}function saveCard(e){e.preventDefault();const d=new FormData(e.target),changes={name:d.get('name').trim(),album:d.get('album').trim(),member:d.get('member'),private:d.has('private')};if(state.modal.card.id)Object.assign(state.cards.find(c=>c.id===state.modal.card.id),changes);else state.cards.unshift({id:Date.now(),style:'',...changes});persist();state.modal=null;render()}function togglePrivate(id){const c=state.cards.find(c=>c.id===id);c.private=!c.private;state.menuId=null;persist();render()}function deleteCard(id){if(confirm('이 포카를 리스트에서 삭제할까요?')){state.cards=state.cards.filter(c=>c.id!==id);state.menuId=null;persist();render()}}function changeImage(id){state.menuId=null;state.fileTarget=id;render();picker.click()}
picker.addEventListener('change',e=>{const file=e.target.files[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{state.cards.find(c=>c.id===state.fileTarget).image=reader.result;persist();render()};reader.readAsDataURL(file);e.target.value=''});
render();

