// 이 사이트는 로그인 없이 관리자 컬렉션으로 바로 시작합니다.
// 공개 저장소에 비밀번호를 보관하지 않습니다.
const ADMIN = { id: 'Jane2026_helloW', password: '' };
const MEMBERS = ['방찬', '리노', '창빈', '현진', '한', '필릭스', '승민', '아이엔'];
const seed = [
  {id:1,name:'5-STAR 한정 포토카드',album:'★★★★★ (5-STAR)',member:'방찬',style:'',private:false},
  {id:2,name:'樂-STAR 락스타 포카',album:'樂-STAR',member:'리노',style:'alt',private:false},
  {id:3,name:'ATE 미공포',album:'ATE',member:'현진',style:'warm',private:false},
  {id:4,name:'ODDINARY 스캔 포카',album:'ODDINARY',member:'필릭스',style:'alt',private:true},
  {id:5,name:'MAXIDENT 특전 포카',album:'MAXIDENT',member:'승민',style:'warm',private:false},
  {id:6,name:'GIANT 일본반 포카',album:'GIANT',member:'아이엔',style:'',private:false}
];
let state = {user:{name:ADMIN.id,admin:true}, mode:'login', cards:JSON.parse(localStorage.getItem('skz-cards') || 'null') || seed, query:'', member:'전체 멤버', album:'전체 앨범', modal:null, menu:null};
// 로그인 화면을 건너뛰고, 파일을 열면 곧바로 관리자 컬렉션을 보여준다.
setTimeout(() => { window.logout = () => render(); render(); }, 0);
const root = document.querySelector('#app');
const saveCards=()=>localStorage.setItem('skz-cards',JSON.stringify(state.cards));
const esc=s=>String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function login(){ root.innerHTML=`<section class="login-page"><aside class="login-art"><div class="brand">SKZ ARCHIVE</div><div class="deco-card"></div><div class="art-title">YOUR<br><em>PHOTOCARD</em><br>UNIVERSE.</div></aside><section class="login-panel"><div class="login-box"><h1>안녕하세요!</h1><p>나만의 스트레이키즈 포카 리스트를 만들어보세요.</p><div class="tabs"><button class="${state.mode==='login'?'active':''}" onclick="setMode('login')">로그인</button><button class="${state.mode==='signup'?'active':''}" onclick="setMode('signup')">회원가입</button></div><form onsubmit="auth(event)"><div class="field"><label>아이디</label><input id="id" required autocomplete="username" placeholder="아이디를 입력하세요" /></div><div class="field"><label>비밀번호</label><input id="pw" type="password" required autocomplete="current-password" placeholder="비밀번호를 입력하세요" /></div><button class="primary">${state.mode==='login'?'로그인':'간편 회원가입'}</button></form>${state.mode==='login'?'<button class="quick-admin" onclick="quickAdmin()">관리자 모드로 바로 시작</button>':''}<button class="guest" onclick="enterGuest()">게스트로 둘러보기 →</button><div class="error" id="error"></div><div class="hint">휴대폰 번호나 이메일 없이, 아이디와 비밀번호만 있으면 충분해요.</div></div></section></section>` }
function setMode(mode){state.mode=mode;login()}
function auth(e){e.preventDefault();const id=document.querySelector('#id').value.trim(),pw=document.querySelector('#pw').value.trim();if(state.mode==='login'&&id===ADMIN.id&&pw===ADMIN.password){state.user={name:id,admin:true};render();return}if(state.mode==='signup'){state.user={name:id,admin:false};render();return}document.querySelector('#error').textContent='아이디 또는 비밀번호를 확인해 주세요. 새 계정은 회원가입 탭에서 만들 수 있어요.'}
function quickAdmin(){state.user={name:ADMIN.id,admin:true};render()}
function enterGuest(){state.user={name:'게스트',admin:false,guest:true};render()}
function render(){const albums=[...new Set(state.cards.map(x=>x.album))];const filtered=state.cards.filter(c=>(!state.query||`${c.name} ${c.album} ${c.member}`.toLowerCase().includes(state.query.toLowerCase()))&&(state.member==='전체 멤버'||c.member===state.member)&&(state.album==='전체 앨범'||c.album===state.album)&&(!state.user.guest||!c.private));root.innerHTML=`<div class="app-shell"><header class="topbar"><div class="brand">SKZ ARCHIVE</div><div class="profile"><div class="avatar">${esc(state.user.name[0])}</div><span>${esc(state.user.name)}</span>${state.user.admin?'<span class="badge">ADMIN</span>':''}<button class="logout" onclick="logout()">나가기</button></div></header><section class="intro"><div><h1>포카 리스트</h1><p>${state.user.guest?'게스트로 공개 포카를 보고 있어요.':'나의 스트레이키즈 컬렉션을 한 곳에서 관리하세요.'}</p></div><div class="count">${filtered.length} CARDS</div></section><section class="controls"><input class="search" value="${esc(state.query)}" oninput="state.query=this.value;render()" placeholder="포카, 앨범, 멤버 검색" /><select class="filter" onchange="state.member=this.value;render()"><option>전체 멤버</option>${MEMBERS.map(m=>`<option ${state.member===m?'selected':''}>${m}</option>`).join('')}</select><select class="filter" onchange="state.album=this.value;render()"><option>전체 앨범</option>${albums.map(a=>`<option ${state.album===a?'selected':''}>${esc(a)}</option>`).join('')}</select>${state.user.admin?'<button class="add" onclick="openAdd()">+ 포카 추가</button>':''}</section><section class="grid">${filtered.length?filtered.map(card).join(''):'<div class="empty">조건에 맞는 포카가 없어요.</div>'}</section></div>${state.modal?modal():''}`}
function card(c){return `<article class="pc-card"><div class="pc-image ${c.style||''}">${c.image?`<img src="${c.image}" alt="" style="width:100%;height:100%;object-fit:cover">`:'✦'}</div>${c.private?'<span class="private">🔒 비공개</span>':''}${state.user.admin?`<button class="dots" onclick="toggleMenu(${c.id})">⋮</button>${state.menu===c.id?`<div class="menu"><button onclick="editCard(${c.id})">이름 변경</button><button onclick="changeImage(${c.id})">파일 변경</button><button onclick="togglePrivate(${c.id})">${c.private?'공개로 전환':'비공개 전환'}</button><button class="danger" onclick="deleteCard(${c.id})">삭제</button></div>`:''}`:''}<div class="pc-info"><div class="member">${esc(c.member)}</div><div class="pc-name">${esc(c.name)}</div><div class="album">${esc(c.album)}</div></div></article>`}
function modal(){const c=state.modal.card||{};return `<div class="modal-backdrop" onclick="if(event.target===this)closeModal()"><form class="modal" onsubmit="saveCard(event)"><h2>${c.id?'포카 수정':'새 포카 추가'}</h2><div class="field"><label>포카 이름</label><input name="name" required value="${esc(c.name||'')}" placeholder="예: ATE 사운드웨이브 특전" /></div><div class="field"><label>앨범</label><input name="album" required value="${esc(c.album||'')}" placeholder="예: ATE" /></div><div class="field"><label>멤버 선택</label><select name="member">${MEMBERS.map(m=>`<option ${c.member===m?'selected':''}>${m}</option>`).join('')}</select></div><div class="field"><label><input type="checkbox" name="private" ${c.private?'checked':''}/> 비공개 포카로 등록</label></div><div class="modal-actions"><button type="button" class="cancel" onclick="closeModal()">취소</button><button class="save">저장하기</button></div></form></div>`}
function openAdd(){state.modal={card:{member:MEMBERS[0]}};render()}function editCard(id){state.menu=null;state.modal={card:{...state.cards.find(c=>c.id===id)}};render()}function closeModal(){state.modal=null;render()}function saveCard(e){e.preventDefault();const f=new FormData(e.target),incoming={name:f.get('name').trim(),album:f.get('album').trim(),member:f.get('member'),private:f.has('private')};if(state.modal.card.id){Object.assign(state.cards.find(c=>c.id===state.modal.card.id),incoming)}else state.cards.unshift({id:Date.now(),style:'',...incoming});saveCards();state.modal=null;render()}function toggleMenu(id){state.menu=state.menu===id?null:id;render()}function togglePrivate(id){const c=state.cards.find(c=>c.id===id);c.private=!c.private;state.menu=null;saveCards();render()}function deleteCard(id){if(confirm('이 포카를 리스트에서 삭제할까요?')){state.cards=state.cards.filter(c=>c.id!==id);saveCards();state.menu=null;render()}}function changeImage(id){state.menu=null;state.fileTarget=id;document.querySelector('#file-picker').click();render()}document.querySelector('#file-picker').addEventListener('change',e=>{const file=e.target.files[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{state.cards.find(c=>c.id===state.fileTarget).image=reader.result;saveCards();render()};reader.readAsDataURL(file);e.target.value=''})function logout(){state.user=null;state.mode='login';state.menu=null;login()}login();

